// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ParqueDbContext))]
    [Migration("20251120121426_yo")]
    partial class yo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Entities.AccesoAtraccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtraccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaHoraEgreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraIngreso")
                        .HasColumnType("datetime2");

                    b.Property<int>("PuntosObtenidos")
                        .HasColumnType("int");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VisitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("AtraccionId", "FechaHoraIngreso");

                    b.HasIndex("VisitanteId", "FechaHoraIngreso");

                    b.ToTable("AccesosAtraccion");
                });

            modelBuilder.Entity("Dominio.Entities.Atraccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<int>("EdadMinima")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Atracciones", t =>
                        {
                            t.HasCheckConstraint("CK_Atraccion_CapacidadMaxima", "CapacidadMaxima >= 1");

                            t.HasCheckConstraint("CK_Atraccion_EdadMinima", "EdadMinima >= 0");
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Canje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCanje")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecompensaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecompensaId");

                    b.HasIndex("UsuarioId", "RecompensaId", "FechaCanje");

                    b.ToTable("Canjes");
                });

            modelBuilder.Entity("Dominio.Entities.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Aforo")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoAdicional")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<long>("Hora")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre", "Fecha", "Hora")
                        .IsUnique();

                    b.ToTable("Eventos", t =>
                        {
                            t.HasCheckConstraint("CK_Evento_Aforo", "Aforo >= 1");

                            t.HasCheckConstraint("CK_Evento_Costo", "CostoAdicional >= 0");
                        });
                });

            modelBuilder.Entity("Dominio.Entities.HistorialPuntuacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstrategiaActiva")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<Guid>("VisitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VisitanteId", "FechaHora");

                    b.ToTable("HistorialesPuntuacion");
                });

            modelBuilder.Entity("Dominio.Entities.Incidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtraccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit");

                    b.Property<string>("TipoIncidencia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AtraccionId", "EstaActiva");

                    b.ToTable("Incidencias");

                    b.HasDiscriminator().HasValue("Incidencia");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dominio.Entities.Recompensa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<int>("Costo")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("NivelRequerido")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Recompensas");
                });

            modelBuilder.Entity("Dominio.Entities.Reloj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Relojes");
                });

            modelBuilder.Entity("Dominio.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EventoAsociadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaVisita")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoEntrada")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("VisitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventoAsociadoId");

                    b.HasIndex("VisitanteId", "FechaVisita");

                    b.ToTable("Tickets", t =>
                        {
                            t.HasCheckConstraint("CK_Ticket_EventoEspecial_Requiere_Evento", "(TipoEntrada <> 'EventoEspecial') OR (EventoAsociadoId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Dominio.Entities.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EventoAtracciones", b =>
                {
                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtraccionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventoId", "AtraccionId");

                    b.HasIndex("AtraccionId");

                    b.ToTable("EventoAtracciones");
                });

            modelBuilder.Entity("Dominio.Entities.MantenimientoPreventivo", b =>
                {
                    b.HasBaseType("Dominio.Entities.Incidencia");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("MantenimientoPreventivo");
                });

            modelBuilder.Entity("Dominio.Entities.Usuarios.Administrador", b =>
                {
                    b.HasBaseType("Dominio.Entities.Usuarios.Usuario");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("Dominio.Entities.Usuarios.Operador", b =>
                {
                    b.HasBaseType("Dominio.Entities.Usuarios.Usuario");

                    b.HasDiscriminator().HasValue("Operador");
                });

            modelBuilder.Entity("Dominio.Entities.Usuarios.Visitante", b =>
                {
                    b.HasBaseType("Dominio.Entities.Usuarios.Usuario");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NfcId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NivelMembresia")
                        .HasColumnType("int");

                    b.Property<int>("PuntosActuales")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Visitante");
                });

            modelBuilder.Entity("Dominio.Entities.AccesoAtraccion", b =>
                {
                    b.HasOne("Dominio.Entities.Atraccion", "Atraccion")
                        .WithMany()
                        .HasForeignKey("AtraccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Usuarios.Visitante", "Visitante")
                        .WithMany()
                        .HasForeignKey("VisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Ticket");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("Dominio.Entities.Canje", b =>
                {
                    b.HasOne("Dominio.Entities.Recompensa", "Recompensa")
                        .WithMany()
                        .HasForeignKey("RecompensaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recompensa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dominio.Entities.HistorialPuntuacion", b =>
                {
                    b.HasOne("Dominio.Entities.Usuarios.Visitante", "Visitante")
                        .WithMany()
                        .HasForeignKey("VisitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("Dominio.Entities.Incidencia", b =>
                {
                    b.HasOne("Dominio.Entities.Atraccion", "Atraccion")
                        .WithMany("Incidencias")
                        .HasForeignKey("AtraccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("Dominio.Entities.Ticket", b =>
                {
                    b.HasOne("Dominio.Entities.Evento", "EventoAsociado")
                        .WithMany()
                        .HasForeignKey("EventoAsociadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dominio.Entities.Usuarios.Visitante", "Visitante")
                        .WithMany()
                        .HasForeignKey("VisitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventoAsociado");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("Dominio.Entities.Usuarios.Usuario", b =>
                {
                    b.OwnsOne("Dominio.ValueObjects.Contrasenia", "Contrasenia", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ContraseniaHash");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Contrasenia")
                        .IsRequired();
                });

            modelBuilder.Entity("EventoAtracciones", b =>
                {
                    b.HasOne("Dominio.Entities.Atraccion", null)
                        .WithMany()
                        .HasForeignKey("AtraccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entities.Evento", null)
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Entities.Atraccion", b =>
                {
                    b.Navigation("Incidencias");
                });
#pragma warning restore 612, 618
        }
    }
}
